export const GET_ALL_ALBUMS_REQUEST = "GET_ALL_ALBUMS_REQUEST";
export const GET_ALL_ALBUMS_SUCCESS = "GET_ALL_ALBUMS_SUCCESS";
export const GET_ALL_ALBUMS_FAIL = "GET_ALL_ALBUMS_FAIL";

export const CREATE_ALBUM_REQUEST = "CREATE_ALBUM_REQUEST";
export const CREATE_ALBUM_SUCCESS = "CREATE_ALBUM_SUCCESS";
export const CREATE_ALBUM_FAIL = "CREATE_ALBUM_FAIL";
export const CREATE_ALBUM_RESET = "CREATE_ALBUM_RESET";

export const UPDATE_ALBUM_REQUEST = "UPDATE_ALBUM_REQUEST";
export const UPDATE_ALBUM_SUCCESS = "UPDATE_ALBUM_SUCCESS";
export const UPDATE_ALBUM_FAIL = "UPDATE_ALBUM_FAIL";
export const UPDATE_ALBUM_RESET = "UPDATE_ALBUM_RESET";

export const DELETE_ALBUM_REQUEST = "DELETE_ALBUM_REQUEST";
export const DELETE_ALBUM_SUCCESS = "DELETE_ALBUM_SUCCESS";
export const DELETE_ALBUM_FAIL = "DELETE_ALBUM_FAIL";
export const DELETE_ALBUM_RESET = "DELETE_ALBUM_RESET";
