export const SONGS_LIST_REQUEST = "SONGS_LIST_REQUEST";
export const SONGS_LIST_SUCCESS = "SONGS_LIST_SUCCESS";
export const SONGS_LIST_FAIL = "SONGS_LIST_FAIL";

export const SONGS_RANDOM_REQUEST = "SONGS_RANDOM_REQUEST";
export const SONGS_RANDOM_SUCCESS = "SONGS_RANDOM_SUCCESS";
export const SONGS_RANDOM_FAIL = "SONGS_RANDOM_FAIL";

export const SONGS_DETAILS_REQUEST = "SONGS_DETAILS_REQUEST";
export const SONGS_DETAILS_SUCCESS = "SONGS_DETAILS_SUCCESS";
export const SONGS_DETAILS_FAIL = "SONGS_DETAILS_FAIL";
export const SONGS_DETAILS_RESET = "SONGS_DETAILS_RESET";

export const SONGS_TOP_RATED_REQUEST = "SONGS_TOP_RATED_REQUEST";
export const SONGS_TOP_RATED_SUCCESS = "SONGS_TOP_RATED_SUCCESS";
export const SONGS_TOP_RATED_FAIL = "SONGS_TOP_RATED_FAIL";

export const CREATE_REVIEW_REQUEST = "SONGS_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "SONGS_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "SONGS_REVIEW_FAIL";
export const CREATE_REVIEW_RESET = "SONGS_REVIEW_RESET";

export const DELETE_SONG_REQUEST = "DELETE_SONG_REQUEST";
export const DELETE_SONG_SUCCESS = "DELETE_SONG_SUCCESS";
export const DELETE_SONG_FAIL = "DELETE_SONG_FAIL";

export const DELETE_ALL_SONGS_REQUEST = "DELETE_ALL_SONGS_REQUEST";
export const DELETE_ALL_SONGS_SUCCESS = "DELETE_ALL_SONGS_SUCCESS";
export const DELETE_ALL_SONGS_FAIL = "DELETE_ALL_SONGS_FAIL";
